AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'web/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Max: 200

Naming/FileName:
  Exclude:
    - Gemfile

Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'
