version: '3'

services:
  api: &API
    build:
      context: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - 4001:3000
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - web_node_modules:/app/web/node_modules
      - vendor_bundle:/app/vendor/bundle
    stdin_open: true
    tty: true
    depends_on:
      - postgresql

  web:
    <<: *API
    ports:
      - 4000:3000
    command: bash -c "cd web; yarn start"
    depends_on:
      - api

  postgresql:
    tty: false
    image: postgres:11.10
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=fcultimate
      - POSTGRES_USER=fcultimate
      - POSTGRES_DB=fcultimate_${RAILS_ENV}

volumes:
  postgres: {}
  app_node_modules: {}
  web_node_modules: {}
  vendor_bundle: {}
